version: '3'
services:
  app-front:
    build:
      context: ../
      dockerfile: ./docker-octface/app-front/Dockerfile
      args:
        docker_root: ./docker-octface
        app_root:    .
    container_name: app-front
    restart: always
    ports:
      - "8080:80"
  app-bridge:
    build: 
      context: ../
      dockerfile: ./docker-octface/app-bridge/Dockerfile
      args:
        docker_root: ./docker-octface
        app_root:    .
    ports:
      - "3000:3000"
  proxy:
    image: nginx:1.15.3
    container_name: proxy
    privileged: true
    ports:
      - "80:80"
    volumes: 
      - ./proxy/conf/default.conf:/etc/nginx/conf.d/default.conf
#     -  /var/octface/nginx/htpasswd:/etc/nginx/htpasswd
#    network_mode: "bridge"
    restart: always
    links:
      - app-front
      - app-bridge
    
